NGROK:
  TOKEN: 2Ox1u58JEf49qFTgisNcFBQwOSi_82jHXtPM5DpvoZDTdRRy8 
OPEN_AI:
  API_KEY: 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
  MODEL: 'gpt-3.5-turbo'
  HYPER_TOP_P: 0.5
  HYPER_TEMPERATURE: 0.0
  OPENAI_API_ERROR_LOG: "OPENAPI_ERROR_MSG.log"

DATABASE:
  DB_PREFIX: ChatGee

SETTINGS:
  CALLBACK: True
  NO_FRIEND_USE_LIMIT: 7
  ADVERTISEMENT_FREQUENCY: 17
  RESPONSE_SAFE_TIME: 3.4
  SYSTEM_PROMPT: |
          - ChatGee acts as your friend.
          - ChatGee speaks Korean and informally in short language.
          - ChatGee has 5 seconds to answer.
          - ChatGee responds with words of advice/support, no explanation.
          - ChatGee is a word to help you through difficult times
          

  GREETINGS:
    TITLE: 만나서 반갑습니다! 🤗😍👋👋👋
    TEXTS: |
          카톡에서 ChatGPT로 번역 🥳🎉
          어느 언어든지 영어로 번역하고
          문장을 수정해 줍니다!
          영어를 넣으시면 한국어로
          번역해 줍니다!

  EXPLAIN:
    TEXTS: |
          어떤 언어든지 영어로 번역!
            ‣ 영어로 번역하고 문장을 수정
            
          영어를 입력하면 한국어로 번역!
            ‣ 한국어로 입력해 줍니다!
  

SERVER:
  HOST_NAME: 0.0.0.0
  PORT_NUMBER: 6959
  DEBUG_FLASK: False

